<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" total="23" passed="14">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8694" started-at="2017-05-03T08:56:25Z" finished-at="2017-05-03T08:56:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8694" started-at="2017-05-03T08:56:25Z" finished-at="2017-05-03T08:56:33Z">
      <class name="com.cif.restfull_jenkins.AssertClass">
        <test-method status="PASS" signature="getApplyNo()[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="getApplyNo" is-config="true" duration-ms="9" started-at="2017-05-03T16:56:25Z" finished-at="2017-05-03T16:56:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplyNo -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="3494" started-at="2017-05-03T16:56:25Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"mobile_info.voices\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_1","id":"1","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="301" started-at="2017-05-03T16:56:29Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"mobile_info.contacts_intersectphones\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_2","id":"2","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="142" started-at="2017-05-03T16:56:29Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_card_info.credit_basic\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_3","id":"3","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="71" started-at="2017-05-03T16:56:29Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_card_info.trans_info\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_4","id":"4","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="110" started-at="2017-05-03T16:56:29Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"bank_card_info.trans\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_5","id":"5","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="157" started-at="2017-05-03T16:56:30Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"bank_card_info.bank_card_basic\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_6","id":"6","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="175" started-at="2017-05-03T16:56:30Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"alipay_info.contacts\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_7","id":"7","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="204" started-at="2017-05-03T16:56:30Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"alipay_info.alipay_basic\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_8","id":"8","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="127" started-at="2017-05-03T16:56:30Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"alipay_info.alipay_bank\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_9","id":"9","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="287" started-at="2017-05-03T16:56:30Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"taobao_info.address_mark\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_10","id":"10","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="213" started-at="2017-05-03T16:56:31Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"taobao_info.received_address\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_11","id":"11","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="201" started-at="2017-05-03T16:56:31Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"taobao_info.taobao_basic\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_12","id":"12","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="316" started-at="2017-05-03T16:56:31Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"taobao_info.detail_trans_basic\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_13","id":"13","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="364" started-at="2017-05-03T16:56:31Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"basic_info.customer_bank_card\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_14","id":"14","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="292" started-at="2017-05-03T16:56:32Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"basic_info.band_repay_bankcard\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_15","id":"15","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="646" started-at="2017-05-03T16:56:32Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"basic_info.band_borrow_bankcard\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_16","id":"16","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="132" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"basic_info.band_bankcard_mobile\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_17","id":"17","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="PASS" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="172" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"basic_info.band_bankcard_idcardnum\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_18","id":"18","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="136" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_report_info.cr_basic\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_19","id":"19","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="157" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_report_info.query_info\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_20","id":"20","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="61" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_report_info.info_summary\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_21","id":"21","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="76" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_report_info.info_other_overdue\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_22","id":"22","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method status="FAIL" signature="method(com.alibaba.fastjson.JSONObject)[pri:0, instance:com.cif.restfull_jenkins.AssertClass@35bbe5e8]" name="method" duration-ms="124" started-at="2017-05-03T16:56:33Z" data-provider="mysql_retsfull_data" finished-at="2017-05-03T16:56:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{"code":"resultCode","code_1":"tag","expecteds_1":"1","channel":"qz","leval":"P1","params":"{\"idCardNum\":\"idCardNum_change\",\"type\":\"credit_report_info.info_other_normal\"}","type":"json","message":"","url":"api/v1/getOneBasicColumn","expecteds":"SUCCESS","caseID":"case_23","id":"23","table":"resfull_case"}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cif.restfull_jenkins.AssertClass.method(AssertClass.java:27)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
      </class> <!-- com.cif.restfull_jenkins.AssertClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
